language: python

dist: xenial

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy2.7-6.0
  - pypy3.5-6.0

os:
  - linux

install:
  - pip install tox-travis
  - pip install -e .[dev]

script:
  - tox

after_success:
  - tox -e codecov
  - python boots.py create
  - python boots.py build
  - python boots.py publish
