trigger:
  - master

jobs:
  - job: build_wheel
    displayName: Build Wheel and sdist
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - bash: |
          python -m pip install wheel
          python setup.py sdist
          python setup.py bdist_wheel
        displayName: Build Wheel
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'dist'
          targetPath: '$(System.DefaultWorkingDirectory)/dist/'

  - template: azure_job_template.yml
    parameters:
      platform: Linux
      vmImage: 'ubuntu-16.04'
      dependsOn: build_wheel

  - template: azure_job_template.yml
    parameters:
      platform: macOS
      vmImage: 'macOS-10.13'
      dependsOn: build_wheel

  - template: azure_job_template.yml
    parameters:
      platform: Windows
      vmImage: 'vs2017-win2016'
      dependsOn: build_wheel
