parameters:
  platform: ''
  vmImage: ''
  url: ''
  extracter: ''
  version: ''

jobs:
- job: PyPy_${{ parameters.version }}_${{ parameters.platform }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  steps:
    - script: |
        echo '##vso[task.setvariable variable=PATH]$(PATH);$(PWD)/pypy.tmp/pypy'
        mkdir pypy.tmp
        cd pypy.tmp
        curl --location --output archive '${{ parameters.url }}'
        '${{ parameters.extracter }}' archive
        rm archive
        mv ./* pypy
        cd ..
        ll pypy.tmp/pypy
        echo $(PATH)
        type pypy
        pypy --version
      displayName: 'Get PyPy'
    - script: |
        ll pypy.tmp/pypy
        echo $(PATH)
        type pypy
        pypy --version
      displayName: 'Check for PyPy'
    - script: |
        pypy -m pip install tox pytest-azurepipelines
        pypy -m tox -e $(tox.env)
        pypy -m tox -e codecov
      displayName: 'Test'
      env:
        CODECOV_TOKEN: '$(CODECOV_TOKEN)'


