parameters:
  platform: ''
  vmImage: ''
  dependsOn: ''

jobs:
- job: ${{ parameters.platform }}
  displayName: ${{ parameters.platform }}
  dependsOn: ${{ parameters.dependsOn }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    matrix:
      2_7:
        python.version: '2.7'
        python.architecture: 'x64'
        tox.env: 'py27'
      3_4:
        python.version: '3.4'
        python.architecture: 'x64'
        tox.env: 'py34'
      3_5:
        python.version: '3.5'
        python.architecture: 'x64'
        tox.env: 'py35'
      3_6:
        python.version: '3.6'
        python.architecture: 'x64'
        tox.env: 'py36'
      3_7:
        python.version: '3.7'
        python.architecture: 'x64'
        tox.env: 'py37'
      pypy:
        python.version: 'pypy'
        python.architecture: 'x64'
        tox.env: 'pypy'
      pypy3:
        python.version: 'pypy3'
        python.architecture: 'x64'
        tox.env: 'pypy3'      
    maxParallel: 4

  steps:
    - template: azure-download_artifact_step_template.yml
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: '$(python.architecture)'
    - bash: |
        python -m pip install tox pytest-azurepipelines
        python -m tox -e $(tox.env) --installpkg dist/*.whl
      displayName: 'Test'
    - bash: |
        python -m tox -e codecov
      displayName: 'Upload Coverage'
      env:
        CODECOV_TOKEN: '$(CODECOV_TOKEN)'
