trigger:
  - master

jobs:
  - job: build_wheel
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'
      - bash: |
          python -m pip install wheel
          python setup.py sdist
          python setup.py bdist_wheel
          pwd
          ls -l
          ls -l dist
        displayName: Build Wheel
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'dist'
          targetPath: '$(System.DefaultWorkingDirectory)/dist/'

  - template: azure-cpython_job_template.yml
    parameters:
      platform: Linux
      vmImage: 'ubuntu-16.04'
      dependsOn: build_wheel

  - template: azure-pypy_job_template.yml
    parameters:
      platform: Linux
      vmImage: 'ubuntu-16.04'
      url_2: 'https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-linux64.tar.bz2'
      url_3: 'https://bitbucket.org/pypy/pypy/downloads/pypy3.5-v7.0.0-linux64.tar.bz2'
      extracter: 'tar -xvf'
      dependsOn: build_wheel

  - template: azure-cpython_job_template.yml
    parameters:
      platform: macOS
      vmImage: 'macOS-10.13'
      dependsOn: build_wheel

  - template: azure-pypy_job_template.yml
    parameters:
      platform: macOS
      vmImage: 'macOS-10.13'
      url_2: 'https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-osx64.tar.bz2'
      url_3: 'https://bitbucket.org/pypy/pypy/downloads/pypy3.5-v7.0.0-osx64.tar.bz2'
      extracter: 'tar -xvf'
      dependsOn: build_wheel

  - template: azure-cpython_job_template.yml
    parameters:
      platform: Windows
      vmImage: 'vs2017-win2016'
      dependsOn: build_wheel

  - template: azure-pypy_job_template.yml
    parameters:
      platform: Windows
      vmImage: 'vs2017-win2016'
      url_2: 'https://bitbucket.org/pypy/pypy/downloads/pypy2.7-v7.0.0-win32.zip'
      url_3: 'https://bitbucket.org/pypy/pypy/downloads/pypy3.5-v7.0.0-win32.zip'
      extracter: 'unzip'
      dependsOn: build_wheel
