parameters:
  platform: ''
  vmImage: ''
  url_2: ''
  url_3: ''
  extracter: ''
  version: ''

jobs:
- job: PyPy_${{ parameters.platform }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    matrix:
      2_7:
        url: ${{ parameters.url_2 }}
        tox.env: 'pypy'
      3_5:
        url: ${{ parameters.url_3 }}
        tox.env: 'pypy3'

  steps:
    - bash: |
        echo PATH: ${PATH}
        echo "##vso[task.setvariable variable=PATH]${PWD}/pypy.tmp/pypy/bin:${PWD}/pypy.tmp/pypy:${PATH}"
        mkdir pypy.tmp
        cd pypy.tmp
        curl --location --output archive $(url)
        ${{ parameters.extracter }} archive
        rm archive
        mv ./* pypy
        cd ..
        ls -l pypy.tmp/pypy
      displayName: 'Get PyPy'
    - bash: |
        ls -l pypy.tmp/pypy
        echo PATH: ${PATH}
        type pypy
        pypy --version
      displayName: 'Check for PyPy'
    - bash: |
        pypy -m pip install tox pytest-azurepipelines
        pypy -m tox -e $(tox.env)
        pypy -m tox -e codecov
      displayName: 'Test'
      env:
        CODECOV_TOKEN: '$(CODECOV_TOKEN)'


