parameters:
  platform: ''
  vmImage: ''
  dependsOn: ''

jobs:
- job: ${{ parameters.platform }}_CPython
  displayName: ${{ parameters.platform }} CPython
  dependsOn: ${{ parameters.dependsOn }}

  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    matrix:
      2.7:
        python.version: '2.7'
        python.architecture: 'x64'
        tox.env: 'py27'
      3.4:
        python.version: '3.4'
        python.architecture: 'x64'
        tox.env: 'py34'
      3.5:
        python.version: '3.5'
        python.architecture: 'x64'
        tox.env: 'py35'
      3.6:
        python.version: '3.6'
        python.architecture: 'x64'
        tox.env: 'py36'
      3.7:
        python.version: '3.7'
        python.architecture: 'x64'
        tox.env: 'py37'
    maxParallel: 4

  steps:
    - template: azure/steps/download_artifact.yml
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: '$(python.architecture)'
    - bash: |
        python -m pip install tox pytest-azurepipelines
        python -m tox -e $(tox.env) --installpkg dist/*.whl
      displayName: 'Test'
    - bash: |
        python -m tox -e codecov
      displayName: 'Upload Coverage'
      env:
        CODECOV_TOKEN: '$(CODECOV_TOKEN)'
